import { Inter } from "next/font/google";
import "./globals.css";
// import Nav from "@/components/Nav";
import Provider from "../components/Provider";
import Nav from "../components/Nav";

const inter = Inter({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  display: "swap",
  variable: "--inter-font",
});

export const metadata = {
  title: "AI Prompets",
  description: "Generated by Ahmed Mangood",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Provider>
          <div className="main">
            <div className="gradient" />
          </div>
          <main className="app">
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
